/*
 * This source file was generated by the Gradle 'init' task
 */
package org.shapes

import org.shapes.domain.Drawable
import org.shapes.domain.Hexagon
import org.shapes.domain.Square
import org.shapes.domain.Traingle

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    val square = Square(length = 6, originX = 6, originY = 6)
    val triangle = Traingle(length = 10, originX = 6, originY = 6)
    val hexagon = Hexagon(length = 6, originX = 10, originY = 10)
    //val shapes: List<Shape> = listOf(square, triangle)

    val shapes: List<Drawable> = listOf(square,triangle, hexagon)
    /*val drawerSquare = drawSquare(square)
    val drawerTriangle = drawTriangle(triangle)
    val drawers: List<Drawable> = listOf(drawerSquare, drawerTriangle)*/


    shapes.onEach {  //forma concisa para recorrer una lista de figuras y dibujar cada una al llamar al metodo draw()
        it.draw()    //it es una forma abreviada de referirse al elemento actual en la iteración (cada Shape).
        //drawer.draw()
        //drawerT.draw()
    }}
