/*
 * This source file was generated by the Gradle 'init' task
 */
package org.shapes

import org.shapes.domain.Square
import org.shapes.domain.Traingle

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

/**
 * args
 *  "square", "triangle", "hexagon"
 */
enum class ShapeInput {
    square,
    triangle,
    hexagon
}

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("No args received")
        return
    }
    args.onEach { shape ->
        when (shape) {
            ShapeInput.square.name -> {
                val square = Square(length = 6, originX = 6, originY = 6)
                square.draw()
            }

            ShapeInput.triangle.name -> {
                val triangle = Traingle(length = 10, originX = 6, originY = 6)
                triangle.draw()
            }

            else -> {
                println("Shape not found.")
            }
        }
    }
}
